Modify data-security to respect OpenEdu methodology
security-summer-school/essentials-security pull request #4
Opened 2024-06-15 01:11 UTC by Jetoson

# Prerequisite Checklist

- [ ] Read the [contribution guidelines](https://github.com/open-education-hub/ccas-internal/blob/main/CONTRIBUTING.md#pull-requests) regarding submitting new changes to the project;
- [ ] Tested your changes against relevant architectures and platforms;
- [ ] Updated relevant documentation (if needed).

## Description of changes

2024-06-16 10:55 UTC, teodutu requested changes
I made an initial pass and given some general feedback. Apart from it, fix the failing CI/CD tests (including deployment) [1]. To fix spellcheck, you'll have to add some words or acronyms to these lists [2]. Make another PR to that repo with the added words. Make sure to run `sort -u -o <file_name> <file_name>`.

[1] https://github.com/security-summer-school/essentials-security/pull/4/checks
[2] https://github.com/open-education-hub/actions/tree/main/spellcheck/config

2024-06-16 10:55 UTC, teodutu commented on data-security/slides/Makefile
> +
```suggestion
```

2024-06-16 10:55 UTC, teodutu commented on data-security/reading/README.md
> +
```suggestion
```
This was only needed for our older rendering engine, but not for Docusaurus.

2024-06-16 10:55 UTC, teodutu commented on data-security/reading/README.md
> +
```suggestion
```

2024-06-16 10:55 UTC, teodutu commented on data-security/reading/README.md
> +
Move this content to `introduction.md`.

2024-06-16 10:55 UTC, teodutu commented on data-security/reading/README.md
> +
Move this content to `xor-encrpytion.md`.

2024-06-16 10:55 UTC, teodutu commented on data-security/reading/README.md
> +
Move this content to `symmetric-cryptography.md`.

2024-06-16 10:55 UTC, teodutu commented on data-security/reading/README.md
> +
```suggestion
```

2024-06-16 10:55 UTC, teodutu commented on data-security/reading/README.md
> +## Further Reading
Either add some interesting links or remove this section. Don't leave it as a stub.

2024-06-16 10:55 UTC, teodutu commented on config.yaml
> +                            - Xor Encryption/: xor-encryption/README.md
```suggestion
                            - Caesar Cipher/: caesar-cipher/README.md
                            - Xor Encryption/: xor-encryption/README.md
                            - AES CBC/: aes-cbc/README.md
```

2024-06-18 09:17 UTC, Jetoson commented
I made the requested changes and opened a PR[1] to fix the failing spellcheck test.

1. https://github.com/open-education-hub/actions/pull/59

2024-06-18 15:10 UTC, teodutu requested changes
Watch out for the super-linter [1] and checkpatch [2] errors. To fix your commit description:

1. First format its title as described in the commit guidelines [3]: `chapters/data-security: Add session content`.
2. Add a description about what the content is about. Use the example commit at [3] as an example.
3. Sign your commit using `git commit --amend -s`.

[1] https://github.com/security-summer-school/essentials-security/actions/runs/9562547309/job/26372997637?pr=4#step:3:989
[2] https://github.com/security-summer-school/essentials-security/actions/runs/9562547309/job/26372998333?pr=4#step:3:534
[3] https://github.com/security-summer-school/essentials-security/blob/main/CONTRIBUTING.md#commits

2024-06-20 15:25 UTC, teodutu requested changes
PR rendering fails because you placed the content directly in the repo's root. Instead, the `data-securty` chapter should be placed in `chapters/data/`. Then you need to remove all `overview` sections from `config.yaml`.

After that, take a look at the automatic tests that are failing [1] [2] and fix them. To fix the checkpatch errors, you'll first have to squash your commits like so:
1. run `git rebase -i main`. It will open your default editor and list all the commits on your branch.
2. Change the first word of all lines except for the first one from `pick` to `s` (from "squash") and save and exit.
3. A new editor tab will open with the commit messages. Reword them like so:
```
data-security: Add session content

Then add a short description of the content
```
4. Run `git commit --amend -s --no-edit` to add your commit signature
5. Finally, run `git push -f` to push your changes upstream.

Amend this new commit for every new revision using `git commit --amend --no-edit`.

[1] https://github.com/security-summer-school/essentials-security/actions/runs/9572698155/job/26392592312?pr=4
[2] https://github.com/security-summer-school/essentials-security/actions/runs/9572698155/job/26392591945?pr=4#step:3:995
[3] https://github.com/security-summer-school/essentials-security/actions/runs/9572698155/job/26392592540?pr=4

2024-06-20 15:25 UTC, teodutu commented on data-security/reading/symmetric-cryptography.md
> +``
```suggestion
```
```

2024-06-20 15:25 UTC, teodutu commented on data-security/reading/symmetric-cryptography.md
> +#Encryption
```suggestion
# Encryption
```

2024-06-20 23:43 UTC, Jetoson commented
Made the requested changes and fixed all `checkpatch` and `super-linter` rerrors. Though the spellcheck tests has passed the PR[1] with few additional words is still open.

1. https://github.com/open-education-hub/actions/pull/60/

2024-06-21 13:48 UTC, teodutu requested changes
The content is good now. I made some small suggestions about sentence formatting. In addition, building the website fails because of the slides. Remove all references to `data-security/slides` from `config.yaml`.

2024-06-21 13:48 UTC, teodutu commented on chapters/data/data-security/drills/tasks/aes-cbc/README.md
> +
```suggestion

Decrypt the string below using the provided key and IV.

```
Describe the task a little bit so it's not so abrupt.

2024-06-21 13:48 UTC, teodutu commented on chapters/data/data-security/drills/tasks/caesar-cipher/README.md
> +Encrypted string: `JJJ{nyp_1j_dp_j4cru_jy1w7vu}`
```suggestion
Decrypt the following string: `JJJ{nyp_1j_dp_j4cru_jy1w7vu}`
```

2024-06-21 13:48 UTC, teodutu commented on chapters/data/data-security/drills/tasks/xor-encryption/README.md
> +Encrypted string: `0x3b3c241f180d4715275b2d332a2b181a015f185a34111f5e041012`
```suggestion
Decrypt the following string: `0x3b3c241f180d4715275b2d332a2b181a015f185a34111f5e041012`
```

2024-06-21 13:48 UTC, teodutu commented on chapters/data/data-security/reading/symmetric-cryptography.md
> +larger than the block size.
```suggestion
Block ciphers seems to solve the OTP key size problem but "what if we want to encrypt more than a block of data?"
We will need to use a block cipher mode of operation.
The mode of operation describes how to securely apply the cipher's single-block operation to transform data larger than the block size.
```

2024-06-21 13:48 UTC, teodutu commented on chapters/data/data-security/reading/symmetric-cryptography.md
> +encrypted separately.
```suggestion
The way it works it's straightforward: the message is divided into multiple blocks and each block is encrypted separately.
```

2024-06-21 13:48 UTC, teodutu commented on chapters/data/data-security/reading/symmetric-cryptography.md
> +block of ciphertext.
```suggestion
The main security issue with ECB mode is that encrypting the same block of plaintext always returns the same block of ciphertext.
```

2024-06-21 13:48 UTC, teodutu commented on chapters/data/data-security/reading/xor-encrpytion.md
> +output is true if either first or second input is true but not both.
```suggestion
Exclusive or, also called "XOR" is a binary operator that behave like an programmable inverter so as the output is true if either first or second input is true but not both.
```

2024-06-21 13:48 UTC, teodutu commented on chapters/data/data-security/reading/xor-encrpytion.md
> +most secure encryption algorithm, called a **one-time pad**.
```suggestion
At a first glance, XOR may look too simple to provide a secure encryption scheme but it is the basis of the most secure encryption algorithm, called a **one-time pad**.
```

2024-06-21 13:48 UTC, teodutu commented on chapters/data/data-security/reading/xor-encrpytion.md
> +and unpredictable bits, the attacker won't have any clue about the plaintext when they see the ciphertext.
```suggestion
Given a plaintext that can be translated into binary data and the previously mentioned pad made up of random and unpredictable bits, the attacker won't have any clue about the plaintext when they see the ciphertext.
```

2024-06-21 13:48 UTC, teodutu commented on chapters/data/data-security/reading/xor-encrpytion.md
> +practical time.
```suggestion
You will probably think "Why don't we use OTP's if it's impossible for an attacker to decipher it if the OTP's rules are implemented correctly?"
The problem is OTP is impractical: if the data you want to transmit is big then the pad must be at least the size of the data.
Also you'll have to transmit the pad to other parties ahead of time in order to get it deciphered in practical time.
```

2024-06-21 13:48 UTC, teodutu commented on chapters/data/data-security/reading/xor-encrpytion.md
> +decryption:
```suggestion
We can combine the previously mentioned properties in order to obtain a cool property that's used for decryption:
```

2024-06-21 13:48 UTC, teodutu commented on chapters/data/data-security/reading/xor-encrpytion.md
> +decryption phase:
```suggestion
The first XOR between $a$ and $b$ is the encryption part whereas the second XOR operations marks the decryption phase:
```

2024-06-21 13:48 UTC, teodutu commented on chapters/data/data-security/reading/xor-encrpytion.md
> +XOR them.
```suggestion
We only defined the XOR as working on single bits, so to be able to use the XOR for encryption we need to implement a bitwise XOR function that can operate on more than one bit.

Luckily, Python already provides us with the `^` (caret) operator that can be applied to integers to XOR them.
```

2024-06-22 07:00 UTC, teodutu approved these changes
:+1: GG!

2024-06-22 07:01 UTC, teodutu commented
@RaresCroicia add your review so we can merge this after it's addressed.

2024-06-22 14:34 UTC, RaresCroicia approved these changes
Seems good to me!

2024-06-23 11:47 UTC, merged