Update binary-analysis for migration
security-summer-school/essentials-security pull request #8
Opened 2024-06-22 14:17 UTC by Mihnea0Firoiu

# Prerequisite Checklist

- [ ] Read the [contribution guidelines](https://github.com/open-education-hub/ccas-internal/blob/main/CONTRIBUTING.md#pull-requests) regarding submitting new changes to the project;
- [ ] Tested your changes against relevant architectures and platforms;
- [ ] Updated relevant documentation (if needed).

## Description of changes

Update binary-analysis for migration.

2024-06-23 12:52 UTC, teodutu requested changes
- At the end of each task's `README.md`, add a sentence like, "If you're having difficulties solving this exercise, go through [this](link to the relevant section in reading/) reading material."
- Add the `src/` folder from each task to `support/` and leave the binary files at the same level as `src/`.

2024-06-23 12:52 UTC, teodutu commented on chapters/binary-introduction/binary-analysis/drills/tasks/easy-to-spot/README.md
> +
```suggestion
```

2024-06-23 12:52 UTC, teodutu commented on chapters/binary-introduction/binary-analysis/drills/tasks/ghidra-killer/README.md
> +
```suggestion
```

2024-06-23 12:52 UTC, teodutu commented on chapters/binary-introduction/binary-analysis/drills/tasks/packaging-is-important/README.md
> +
```suggestion
```

2024-06-23 12:52 UTC, teodutu commented on chapters/binary-introduction/binary-analysis/drills/tasks/spaghetti/README.md
> +
```suggestion
```

2024-06-23 12:54 UTC, teodutu commented
In addition, take a look at the failing CI/CD tests and fix them [1]. For the false positives coming from spellcheck, you'll have to add them here to the wordlists via a PR [2]. Use `sort -u -o <file-name> <file-name>` to keep those wordlists sorted.

[1] https://github.com/security-summer-school/essentials-security/pull/8/checks
[2] https://github.com/open-education-hub/actions/tree/main/spellcheck/config

2024-07-15 15:14 UTC, teodutu requested changes
Just split the reading material into 4 parts and then this should be good to go.

2024-07-15 15:14 UTC, teodutu commented on chapters/binary-introduction/binary-analysis/reading/README.md
Remove the old "header":
```
---
linkTitle: 09. Binary Analysis
type: docs
weight: 10
---
```
And start the file with the first heading. Then split this file into 4 parts:

- `introduction.md` with the Reminders and Introduction
- `static-analysis.md`
- `dynamic-analysis.md`
- `summary.md`

Remember to update the link at the end of each task to point to the right reading material.

2024-07-17 12:55 UTC, teodutu requested changes
Just one more thing for super-linter to pass.

2024-07-17 12:55 UTC, teodutu commented on chapters/binary-introduction/binary-analysis/reading/introduction.md
To pacify super-linter, reverse the order of the sections in this file and turn "Reminders" into a level 2 heading (`##`).

2024-07-17 13:24 UTC, teodutu requested changes
I didn't see the C code files were also flagging super-linter [1]. First rebase the `main` branch because I added a config file for cpplint which will eliminate some of the errors. Then fix the remaining ones.

[1] https://github.com/security-summer-school/essentials-security/actions/runs/9974980826/job/27563650264?pr=8#step:3:625

2024-07-17 13:54 UTC, Mihnea0Firoiu commented
> I didn't see the C code files were also flagging super-linter [1]. First rebase the `main` branch because I added a config file for cpplint which will eliminate some of the errors. Then fix the remaining ones.

I rebased it, but that commit doesn't seem to change something regarding how cpplint works.

2024-07-17 16:03 UTC, teodutu commented
> > I didn't see the C code files were also flagging super-linter [1]. First rebase the `main` branch because I added a config file for cpplint which will eliminate some of the errors. Then fix the remaining ones.
> 
> I rebased it, but that commit doesn't seem to change something regarding how cpplint works.

Fuck, you,re right. I had only added `CPPLINT.cfg` to the internal repo. Now I've added it here as well. Rebase again and pull the latest `main` branch locally before doing so.

2024-07-18 09:03 UTC, teodutu approved these changes

2024-07-18 09:03 UTC, merged