Update system-exploration directory
security-summer-school/essentials-security pull request #9
Opened 2024-06-22 14:56 UTC by SorinAlexB

# Prerequisite Checklist

- [ ] Read the [contribution guidelines](https://github.com/open-education-hub/ccas-internal/blob/main/CONTRIBUTING.md#pull-requests) regarding submitting new changes to the project;
- [ ] Tested your changes against relevant architectures and platforms;
- [ ] Updated relevant documentation (if needed).

## Description of changes

Transitioned the 'system-exploration' directory to meet the requirements of the OpenEdu Methodology.

2024-06-23 12:12 UTC, teodutu requested changes
Fix the super-linter errors [1]. I know some of them are annoying (especially those related to shell scripts), but most do make sense. In addition, reword your commit to `scratch-linux/system-exploration: Rework session content according to OpenEdu methodology` then add a description of your changes below.

[1] https://github.com/security-summer-school/essentials-security/actions/runs/9626390655/job/26552309089?pr=9

2024-06-23 12:12 UTC, teodutu commented on chapters/scratch-linux/system-exploration/drills/tasks/doge/README.md
Move this content to `guides/`

2024-06-23 12:12 UTC, teodutu commented on chapters/scratch-linux/system-exploration/reading/README.md
Split this file into:
- `introduction.md` (with the introduction, reminders and prerequisites)
- `exploration-tools.md`: https://security-summer-school.github.io/essentials-security/Scratch%20Linux/System%20Exploration/#continuing-our-exploration
- `file-inspection.md`: https://security-summer-school.github.io/essentials-security/Scratch%20Linux/System%20Exploration/#inspecting-files
- `summary.md`: https://security-summer-school.github.io/essentials-security/Scratch%20Linux/System%20Exploration/#summary
- `further-reading.md`: https://security-summer-school.github.io/essentials-security/Scratch%20Linux/System%20Exploration/#further-reading

2024-06-24 07:11 UTC, teodutu approved these changes
:ok_hand:

2024-06-24 07:13 UTC, teodutu commented
@Ryx076 add your review so we can merge this after your feedback is implemented.

2024-06-24 19:13 UTC, Ryx076 requested changes
Move `drills/tasks/surgical-precision/public` to `drills/tasks/surgical-precision/support`

2024-06-24 19:13 UTC, Ryx076 commented on chapters/scratch-linux/system-exploration/drills/tasks/not-your-doge/solution/solution.py
> +file = open("../public/not-doge.pnm", "rb")
```suggestion
file = open("../../support/not-doge.pnm", "rb")
```

2024-06-24 19:13 UTC, Ryx076 commented on chapters/scratch-linux/system-exploration/drills/tasks/surgical-precision/README.md
> +The answer to each of the riddles in the files `question-*` from the `activities/surgical-precision/public` is the name of one of the given files.
```suggestion
The answer to each of the riddles in the files `question-*` from the `drills/tasks/surgical-precision/support` is the name of one of the given files.
```

2024-06-24 19:13 UTC, Ryx076 commented on chapters/scratch-linux/system-exploration/guides/doge/README.md
> +Head to the `tasks/doge/support` folder and take a look at the image you've been given.
```suggestion
Head to the `guides/doge/support` folder and take a look at the image you've been given.
```

2024-06-24 19:13 UTC, Ryx076 commented on chapters/scratch-linux/system-exploration/guides/doge/README.md
> +root@kali:~/essentials/system-exploration/activities/doge/public# strings doge.jpg
```suggestion
root@kali:~/essentials-security/chapters/scratch-linux/system-exploration/guides/doge/public# strings doge.jpg
```

2024-06-24 19:13 UTC, Ryx076 commented on chapters/scratch-linux/system-exploration/guides/doge/README.md
> +root@kali:~/essentials/system-exploration/activities/doge/public# strings doge.jpg
and the rest

2024-06-24 19:13 UTC, Ryx076 commented on chapters/scratch-linux/system-exploration/reading/file-inspection.md
> +Let's test it using one of today's challenges, `activities/05-challenge_not-your-doge/public/not-doge.pnm`.
```suggestion
Let's test it using one of today's challenges, `drills/tasks/not-your-doge/support/not-doge.pnm`.
```

2024-06-24 19:13 UTC, Ryx076 commented on chapters/scratch-linux/system-exploration/reading/file-inspection.md
> +root@kali:~/essentials/system-exploration# file activities/05-challenge_not-your-doge/public/not-doge.pnm
```suggestion
root@kali:~/essentials-security/chapters/scratch-linux/system-exploration# file drills/tasks/not-your-doge/support/not-doge.pnm
```

2024-06-24 19:13 UTC, Ryx076 commented on chapters/scratch-linux/system-exploration/reading/file-inspection.md
> +activities/05-challenge_not-your-doge/public/not-doge.pnm: Netpbm image data, size = 500 x 590, rawbits, pixmap
```suggestion
drills/tasks/not-your-doge/support/not-doge.pnm: Netpbm image data, size = 500 x 590, rawbits, pixmap
```

2024-06-25 19:18 UTC, Ryx076 approved these changes

2024-06-25 19:20 UTC, merged